Search
Waddix/plexus-create pull request #28
Opened 2021-07-03 21:22 UTC by davidfrnks7

Search works.

Fetches initial data. Uses queries to filter the content from the data.

Projects rendering cards. Need user card, but it doesn't use live data. James is going to refactor user card to use live data. Will update for user cards after.

Inputs are disabled when loading data from db and when db gives errors. Will add alerts with sweet alert during polish week.

2021-07-05 01:40 UTC, bilalhankins submitted a review, later dismissed

2021-07-06 17:34 UTC, OldJamesTown approved these changes

2021-07-06 17:46 UTC, jstrzesz commented on src/pages/search/searchResults.tsx
> +export default function SearchResults({ results, fetching }): JSX.Element {
export default line should be at the end of the file with a new line break after it

2021-07-06 17:46 UTC, jstrzesz requested changes
see comment

2021-07-08 22:15 UTC, davidfrnks7 commented
All changes included with latest PR

2021-07-08 22:15 UTC, closed without merging