Package json fix
Waddix/plexus-create pull request #6
Opened 2021-06-21 22:11 UTC by bilalhankins

2021-06-21 22:16 UTC, jstrzesz requested changes, later dismissed
install husky and create pre-commit and pre-push hooks to run eslint

2021-06-21 22:59 UTC, davidfrnks7 approved these changes, later dismissed

2021-06-22 01:16 UTC, OldJamesTown approved these changes

2021-06-22 01:23 UTC, davidfrnks7 approved these changes

2021-06-22 01:24 UTC, merged